In [1]:
#### Importing all required libraries
import requests
import pandas as pd
from bs4 import BeautifulSoup

base_url = 'https://www.linkedin.com/jobs/search?keywords=Data%20Science&location=Hyderabad%2C%20Telangana%2C%20India&geoId=105556991&trk=public_jobs_jobs-search-bar_search-submit&redirect=false&position=1&pageNum='
list_jobs = []
for pageNo in range(0,40):
    #### Requesting the server to get the content of the web page
    page = requests.get(base_url+str(pageNo*25))
    
    #### Parsing the html
    soup = BeautifulSoup(page.content,'html.parser')
    
    #### Extracting table data using class name
    soup = soup.find_all(class_='result-card__contents job-result-card__contents')
    for i in range(len(soup)):
        dict_jobs={}
        
        #### Extracting 'Title' of the job
        dict_jobs["Title"] = soup[i].find(class_='result-card__title job-result-card__title').text
        
        #### Extracting Name of the 'Company'
        dict_jobs["company"] = soup[i].find(class_='result-card__subtitle job-result-card__subtitle').text
        
        #### Extracting 'Location' of the jon
        dict_jobs["location"] = soup[i].find(class_='job-result-card__location').text
        
        #### Extracting 'date' of the job
        dict_jobs["date"] = soup[i].find('time')['datetime']
        
        list_jobs.append(dict_jobs)

#### Converting all the extracted elements into dataframe
jobs_df = pd.DataFrame(list_jobs)

#### Printing top 5 rows of the data
jobs_df.head()

,Title,company,location,date
0,Full Time Data Science,Microsoft,"Hyderabad, Telangana, India",2020-10-22
1,Data Scientist - 1,Novartis India,"Hyderabad, Telangana, India",2020-11-20
2,Data Scientist,Jio,"Hyderabad, Telangana, India",2020-10-27
3,Data Science,Accenture in India,"Hyderabad, Telangana, India",2020-11-20
4,A&C - Data Science - AI/ML,Deloitte India (Offices of the US),"Hyderabad, Telangana, India",2020-11-04

In [2]:
#### Saving the data in to csv file
jobs_df.to_csv('jobs.csv')